apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kust-nginx
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: kustomize-nginx
    server: https://kubernetes.default.svc
  project: default
  source:
    path: base
    repoURL: https://github.com/hqzhang/argocdtest.git
    targetRevision: master
  syncPolicy:
    automated:
      prune: false
      selfHeal: false

